services:
  heart_db:
    image: timescale/timescaledb:latest-pg16
    container_name: heart_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: heart_db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d heart_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
  mqtt_broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    healthcheck:
      test: [ "CMD", "timeout", "1", "sh", "-c", "nc -z localhost 1883" ]
      interval: 5s
      timeout: 5s
      retries: 5

  heart_sensor:
    build: .
    container_name: heart_sensor
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - MQTT_HOST=mqtt_broker
    command: python sensor_mock.py
    depends_on:
      mqtt_broker:
        condition: service_healthy

  simulation_engine:
    build: .
    container_name: heart_engine
    restart: on-failure
    volumes:
      - ./01_Backend_Simulation:/app
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://user:password@heart_db:5432/heart_db
      - MQTT_HOST=mqtt_broker
    command: python simulation_engine/worker.py
    depends_on:
      heart_db:
        condition: service_healthy
      mqtt_broker:
        condition: service_healthy

  heart_brain:
    build: .
    container_name: heart_brain
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - ./01_Backend_Simulation:/app
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://user:password@heart_db:5432/heart_db
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      heart_db:
        condition: service_healthy

  heart_ingestor:
    build: ./05_Data_Ingestion
    container_name: heart_ingestor
    depends_on:
      - mqtt_broker
    restart: always
